Sprint_4
OlgaSapolgina/Sprint_4 pull request #1
Opened 2023-04-21 22:46 UTC by OlgaSapolgina

2023-04-23 21:20 UTC, kadirovgm requested changes

2023-04-23 21:20 UTC, kadirovgm commented on conftest.py
Отлично! молодец, что пользуешься фикстурами

2023-04-23 21:20 UTC, kadirovgm commented on pages/base_page.py
> +        WebDriverWait(self.driver, 10).until(ec.url_to_be('https://dzen.ru/?yredirect=true'))
Нужно исправить: лучше передавать в аргументы функции url как переменную, таким образом данный метод будет легко переиспользуем для других страницы, а `https://dzen.ru/?yredirect=true` лучше вынести в отдельный файл, например `urls.py`, где будут храниться все статичные данные-ссылки

А в противном случае, это метод страницы main page, если сделать его универсальным, можно оcтавить в base page

2023-04-23 21:20 UTC, kadirovgm commented on pages/base_page.py
> +    def click_order_button_in_header(self):
Нужно исправить: это метод страницы main_page, и не относится к base_page

Напоминаю, по POM мы должны хранить методы страницы в отдельном файле, а в классе `Base Page` храним методы, которые необходимы для манипуляции со всеми страницами, например, скролл до объекта, или "определение наличия объекта" (на любом экране) или "клик по элементу" (любому по переданному параметру)

2023-04-23 21:20 UTC, kadirovgm commented on pages/base_page.py
> +        WebDriverWait(self.driver, 10).until(ec.number_of_windows_to_be(2))
можно лучше: нужно стремиться к переиспользуемости методов в base page, например, здесь можно передавать в аргументы n количество окон, а не всегда считать, что 2

2023-04-23 21:20 UTC, kadirovgm commented on pages/base_page.py
> +    def wait_for_main_page(self):
Нужно исправить: это скорее метод main page, и вообще у тебя уже есть метод `wait_for_page_load`, который можно сделать универсальным и переиспользовать для main page

2023-04-23 21:20 UTC, kadirovgm commented on pages/base_page.py
> +        WebDriverWait(self.driver, 10).until(ec.url_to_be('https://qa-scooter.praktikum-services.ru/'))
Нужно исправить: давай вынесем статичную информацию в отдельный файл, например `urls.py`

2023-04-23 21:20 UTC, kadirovgm commented on pages/main_page.py
> +    def main_page(self):
Нужно исправить: этот метод лучше вынести в `base page`, а в параметры передавать переменную url, таким образом метод , будет уметь открывать любую страницу, ты сможешь его переиспользовать для всех страниц. 

Это нужно, потому что при хорошем код стайле не должно быть повторяющихся мест в коде. Этого надо избегать, пользоваться абстракцией в коде и максимально писать переиспользуемые функции.

2023-04-23 21:20 UTC, kadirovgm commented on pages/main_page.py
> +    def wait_for_main_page(self):
Нужно исправить: у тебя уже есть этот метод в base page, здесь повторять точно нет необходимости, либо оставлять только тут. Но я все же хотел бы, чтобы был общий метод wait_for_page_load, куда бы могла передаваться любая страница

2023-04-23 21:20 UTC, kadirovgm commented on pages/main_page.py
> +        questions[index - 1].click()
Отлично! хорошее решение

2023-04-23 21:20 UTC, kadirovgm commented on pages/order_page.py
> +    def order_page(self):
Можно лучше: 
1. по названию метода неочевидно открытие страницы order, лучше что-то типа open_order_page
2. и я выше писал, что такой метод лучше сделать общим и вынести в base page - для возможности открывать любые страницы одним методом, просто ссылку к странице передавать в аргументы функции

2023-04-23 21:20 UTC, kadirovgm commented on pages/order_page.py
> +    def wait_for_order_page(self):
Можно лучше, то же самое, что в main page, такой метод лучше вынести в base page и сделать общим для переиспользования и чистоты кода

2023-04-23 21:20 UTC, kadirovgm commented on tests/geckodriver.log
Можно лучше: этот файл добавь в gitignore

2023-04-23 21:20 UTC, kadirovgm commented on tests/test_base_page.py
> +        assert driver.current_url == 'https://qa-scooter.praktikum-services.ru/'
Можно лучше: лучше в assert проверять не только, что url правильный после открытия страницы, а еще цепляться за какой то атрибут страницы и проверять его наличие и правильное отображение.

Потому что наличие правильного URL не гарантирует что страница правильно отображается и вообще загрузилась

2023-04-23 21:20 UTC, kadirovgm commented on tests/test_base_page.py
> +        assert driver.current_url == 'https://dzen.ru/?yredirect=true'
Можно лучше: здесь также

2023-04-23 21:20 UTC, kadirovgm commented on tests/test_base_page.py
> +        assert driver.current_url == 'https://dzen.ru/?yredirect=true'
Нужно исправить: статичные данные выносить в отдельный файл, типа urls.py или data.py - таким образом их легко будет менять при дальнейшем масштабировании проекта или изменении данных.

Представь, у тебя этот url в 10 файлах написан и тебе надо везде его поменять, а если бы ты вынесла его в отдельный файл и в тестах обращалась к нему, то пришлось бы поменять только в одном файле.  Когда проект большой, это очень сильно поможет ничего не пропустить при иземенениях

2023-04-23 21:20 UTC, kadirovgm commented on tests/test_main_page.py
> +    questions_list = [
Нужно исправить: статичные тестовые данные лучше выносить в отдельный файл, типа `data.py` и создавать под них там классы и обращаться в тестах к ним.

почему, уже писал в комменте выше

2023-04-23 21:20 UTC, kadirovgm commented on tests/test_main_page.py
> +    @pytest.mark.parametrize("index,text", questions_list)
Отлично! молодец, что воспользовалась здесь параметризацией, тут это четко подходит

2023-04-23 21:20 UTC, kadirovgm commented on tests/test_order_page.py
> +        order.filling_form('Алиса', 'Максимова', 'Ленина ул. 123', 'Люблино',get_phone_number)
Нужно исправить: надо вынести статичные тестовые данные в отдельный файл, уже писал выше почему :)

здесь можно создать отдельный класс под человека

2023-04-23 21:20 UTC, kadirovgm commented on tests/test_order_page.py
> +        order.filling_form('Егор', 'Лапшин', 'Попова ул. 99', 'Аэропорт', get_phone_number)
Нужно исправить: здесь тоже надо вынести в файл

2023-04-23 21:20 UTC, kadirovgm commented on tests/test_order_page.py
> +        order.input_rental_information("09.09.2023", 'two', 'grey', 'no call')
Можно лучше: и здесь :)

2023-04-24 18:56 UTC, OlgaSapolgina commented on pages/base_page.py
> +        WebDriverWait(self.driver, 10).until(ec.url_to_be('https://dzen.ru/?yredirect=true'))
Сделала общий метод для ожидания загрузки страниц, url вынесла в data/urls.py

2023-04-24 18:57 UTC, OlgaSapolgina commented on pages/base_page.py
> +    def click_order_button_in_header(self):
Перенесла в main_page

2023-04-24 18:58 UTC, OlgaSapolgina commented on pages/base_page.py
> +        WebDriverWait(self.driver, 10).until(ec.number_of_windows_to_be(2))
заменила на переменную в методе

2023-04-24 18:59 UTC, OlgaSapolgina commented on pages/base_page.py
> +    def wait_for_main_page(self):
Теперь используется общий метод ожидания загрузки

2023-04-24 19:00 UTC, OlgaSapolgina commented on pages/base_page.py
> +        WebDriverWait(self.driver, 10).until(ec.url_to_be('https://qa-scooter.praktikum-services.ru/'))
Вынесено в data/urls.py

2023-04-24 19:01 UTC, OlgaSapolgina commented on pages/main_page.py
> +    def main_page(self):
Теперь используется общий метод open_page с переменной

2023-04-24 19:02 UTC, OlgaSapolgina commented on pages/main_page.py
> +    def wait_for_main_page(self):
Исправлено, используется общий метод ожидания загрузки

2023-04-24 19:04 UTC, OlgaSapolgina commented on pages/order_page.py
> +    def order_page(self):
Используется общий метод open_page

2023-04-24 19:04 UTC, OlgaSapolgina commented on pages/order_page.py
> +    def wait_for_order_page(self):
Исправлено

2023-04-24 19:05 UTC, OlgaSapolgina commented on tests/geckodriver.log
Добавлен

2023-04-24 19:05 UTC, OlgaSapolgina commented on tests/test_base_page.py
> +        assert driver.current_url == 'https://qa-scooter.praktikum-services.ru/'
Дополнительно добавлена проверка отображения текста на главной странице Самоката

2023-04-24 19:06 UTC, OlgaSapolgina commented on tests/test_base_page.py
> +        assert driver.current_url == 'https://dzen.ru/?yredirect=true'
Вынесено в data/urls.py

2023-04-24 19:07 UTC, OlgaSapolgina commented on tests/test_main_page.py
> +    questions_list = [
в data/data.py

2023-04-24 19:07 UTC, OlgaSapolgina commented on tests/test_order_page.py
> +        order.filling_form('Алиса', 'Максимова', 'Ленина ул. 123', 'Люблино',get_phone_number)
в data/persons.py

2023-04-24 19:08 UTC, OlgaSapolgina commented on tests/test_order_page.py
> +        order.filling_form('Егор', 'Лапшин', 'Попова ул. 99', 'Аэропорт', get_phone_number)
в data/persons.py

2023-04-24 19:08 UTC, OlgaSapolgina commented on tests/test_order_page.py
> +        order.input_rental_information("09.09.2023", 'two', 'grey', 'no call')
в data/data.py

2023-04-25 06:04 UTC, OlgaSapolgina commented on tests/test_base_page.py
> +        assert driver.current_url == 'https://dzen.ru/?yredirect=true'
Оставила как есть

2023-04-26 05:41 UTC, kadirovgm approved these changes

2023-04-26 06:32 UTC, merged